pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step!"
                    chmod 777 gradlew
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                    chmod 777 gradlew
                    ./gradlew sonarqube \
                    -Dsonar.projectKey=merchantofgalaxy1 \
                    -Dsonar.organization=ckant \
                     -Dsonar.host.url=https://sonarcloud.io \
                     -Dsonar.login=92cb17bf23cbb852bd0f16fa1c908f6e4bcf6929
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                    docker build -t mog:1 .
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                bat script: '''
                    echo "I am Publishing DockerImage ="
                    docker tag mog:1 cchandrakant/merchantofgalaxy1
                    docker login -u cchandrakant -p tic@11TOE
                    docker push cchandrakant/merchantofgalaxy1
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}
