pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step!"
                    chmod 777 gradlew
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                    ./gradlew sonarqube \
                    -Dsonar.projectKey=MoGcloud \
                    -Dsonar.organization=ckant \
                    -Dsonar.host.url=https://sonarcloud.io \
                    -Dsonar.login=dcbe74f2fc87cefc282ef888551a123778e37e48
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                bat script: '''
                    echo "I am Building DockerImage ="
                    docker build
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                bat script: '''
                    echo "I am Publishing DockerImage ="
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}