pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat script: '''
                    echo "I am in build step!"
                    chmod 777 gradlew
                    gradlew.bat build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                bat script: '''
                    echo "I am in Test step"
                    gradlew.bat test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                bat script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                bat script: '''
                    echo "I am Building DockerImage ="
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                bat script: '''
                    echo "I am Publishing DockerImage ="
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
}